name: CI-CD Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t devops-cicd-demo .

      - name: Stop old container
        run: docker stop web-demo || true

      - name: Remove old container
        run: docker rm web-demo || true

      - name: Run new container
        run: docker run -d -p 8084:80 --name web-demo devops-cicd-demo
